```{r}
library(Biostrings)
library(stringr)
library(dplyr)
library(ggplot2)
library(kmers.profile)
```

```{r}
k <- 6
x <- 100
size <- "1000000"
```

```{r}
v_fasta_folder <- "../data/virus/all_dengue/"
m_fasta_files <- tools::file_path_sans_ext(list.files(path = "../data/vector/chr1/",full.names = FALSE))

best_kmers_list <- gen_gen_first_obs_kmers(v_fasta_folder,k,x)
# Create Virus dist DF
comb_v_kmer_pos_df <- list() 
v_fasta_files <- tools::file_path_sans_ext(list.files(path = v_fasta_folder ,pattern = "\\.(fasta)$",full.names = FALSE))
for (v_fasta_file in v_fasta_files) {    
  v_kmer_pos_df <- gen_kmers_pos_df(paste(v_fasta_folder,v_fasta_file,".fasta",sep = ""), best_kmers_list,v_fasta_file)
  comb_v_kmer_pos_df[[length(comb_v_kmer_pos_df) + 1]] <- v_kmer_pos_df
}
comb_v_kmer_pos_df <- do.call(rbind, comb_v_kmer_pos_df)

#write.csv(comb_v_kmer_pos_df, file = paste("../data/kmers/g_v_kmer_pos_df.csv",sep = ""), row.names = FALSE) 

# Create Musquito dist DF
all_m_kmer_pos_df <- data.frame()
for (m_fasta_file in m_fasta_files){
  m_kmer_pos_df <- gen_kmers_pos_df(paste("../data/vector/chr1/",m_fasta_file,".fna", sep = ""), best_kmers_list,m_fasta_file)
  write.csv(m_kmer_pos_df, file = paste("../data/kmers/", m_fasta_file, "_kmer_pos_df.csv", sep = ""), row.names = FALSE)
  all_m_kmer_pos_df <- rbind(all_m_kmer_pos_df, m_kmer_pos_df)
}

# GENERATE REFERENCE VALUES

prob <- 1 / (4^k) 
geom_values <- rgeom(100, prob)
log_geom_values <- log10(geom_values + 1)

# GET T_TEST DF

results_df <- get_t_test(comb_v_kmer_pos_df,all_m_kmer_pos_df)
```

```{r}
kmer = "ACATGG"
geom_data <- data.frame(Kmer = "Reference_distribution", 
                         log10_segm_size = log_geom_values)
plot_data <- bind_rows(
  comb_v_kmer_pos_df %>% 
    filter(Kmer == kmer) %>% 
    mutate(Source = Type),
  all_m_kmer_pos_df %>% 
    filter(Kmer == kmer) %>% 
    mutate(Source = "Moustiques"),
  geom_data %>% mutate(Source = "Reference_distribution")
)

means_df <- plot_data %>% 
  group_by(Source) %>% 
  summarise(mean_value = log10(mean(10^(log10_segm_size), na.rm = TRUE)), .groups = 'drop')

line_value <- log10(4^k)

# Reorder the factor levels to ensure virus types appear on the left
plot_data$Source <- factor(plot_data$Source, levels = c(unique(comb_v_kmer_pos_df$Type), "Moustiques", "Reference_distribution"))

# Define the custom colors, setting "Virus" types to the same light blue color
custom_colors <- c(setNames(rep("lightblue", length(unique(comb_v_kmer_pos_df$Type))), unique(comb_v_kmer_pos_df$Type)),
                   "Moustiques" = "darkseagreen2", 
                   "Reference_distribution" = "gray")

na_positions <- plot_data %>%
  filter(is.na(log10_segm_size), Kmer == kmer, Source %in% unique(comb_v_kmer_pos_df$Type)) %>%
  select(Source, Position)

plot <- ggplot(plot_data, aes(x = Source, y = log10_segm_size, fill = Source, color = Source)) +  
  geom_violin(trim = FALSE, scale = "width", alpha = 0.5) +  
  geom_jitter(size = 1, width = 0.2, alpha = 0.3) +  
  geom_point(data = means_df, aes(x = Source, y = mean_value), color = "black", size = 2, shape = 21, fill = "black") +  
  geom_hline(yintercept = line_value, linetype = "dashed", color = "coral") +  
  labs(title = paste("Segment sizes for Kmer: ", kmer," chosen for all Dengue viruses", sep = ""), y = "Log10 Segment Size", x = "") +  
  theme_minimal() +
  ylim(0.8,4.5)+
  theme(legend.position = "none",  
        plot.title = element_text(size = 10, face = "bold"),  
        axis.text.x = element_text(size = 10, angle = 45, hjust = 1),  # Rotate X-axis labels by 30°
        axis.text.y = element_text(size = 10),  
        axis.title.y = element_text(size = 10),  
        panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white")) +  
  scale_fill_manual(values = custom_colors) +  
  scale_color_manual(values = custom_colors) +  
  geom_text(aes(x = 3, y = line_value, label = paste("Expected size using a random ",k,"-mer", sep = "")),  
            color = "coral", vjust = -0.5, size = 4) +  
  geom_jitter(data = na_positions, aes(x = Source, y = log10(Position)), color = "blue", size = 1, width = 0.2, alpha = 0.4, height = 0)
plot
ggsave("../result/violin_plot_all_degnue.png", plot, width = 5, height = 5, dpi = 300)
```
